default: &default
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  template: template0
  pool: <%= Integer(ENV.fetch('RAILS_MAX_THREADS') { 5 }) %>

development:
  <<: *default
  database: team_dashboard_development


test:
  <<: *default
  database: team_dashboard_test


production:
  <<: *default
  database: team_dashboard_production
  username: team_dashboard
  password: <%= ENV['TEAM_DASHBOARD_DATABASE_PASSWORD'] %>
